config/routes.rb
FetchATweet::Application.routes.draw do
  resources :tweets

  root :to => 'tweets#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :content, :tweet_id, :user

  validates :tweet_id, :presence => true
  validates :tweet_id, :uniqueness => true
  validates :tweet_id, :numericality => { :only_integer => true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.paginate(:page => params[:page], :per_page => 10, :order => "created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def create
    tweet_from_twitter = get_tweet_from_twitter(params[:tweet][:tweet_id].to_i)
    @tweet = Tweet.new

    if tweet_from_twitter
      @tweet.user = tweet_from_twitter.user.screen_name
      @tweet.tweet_id = tweet_from_twitter.id
      @tweet.content = tweet_from_twitter.text

      respond_to do |format|
        if @tweet.save
          format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        else
          format.html { render action: "new" }
        end
      end
    else

      @error = "Sorry that tweet doesn't exist. Try again?"
      render :action => 'new'
    end
  end

  protected
    def get_tweet_from_twitter(tweet_id)
      return Twitter.status(tweet_id)
    rescue
      # Could log error or do something else here.
      return nil
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
require 'twitter-text'

module TweetsHelper
    include Twitter::Autolink

    def hyperlink_the_tings(str)
        auto_link(str).html_safe
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fetch A Tweet</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans|Lemon' rel='stylesheet' type='text/css'>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container-narrow">
      <div class="jumbotron">
        <%= link_to "Fetch A Tweet", root_url, :id => 'header' %>
        <p id="lede">Because this is way more fun than working on a cover letter.</p>
      </div>
      <div class="row-fluid">
        <%= yield %>
      </div>
    </div>
    <footer class="container-narrow">
      <div class="span5 offset3">
        <small>Built by <a href="http://aboutaaron.com/">@aboutaaron</a> in Los Angeles. | <a href="http://resume.linkedinlabs.com/z3wen348n">Resume</a></small>
      </div>
    </footer>
    <a href="https://github.com/aboutaaron/fetch-a-tweet"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub"></a>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= simple_form_for @tweet, :html => {:class => 'form-horizontal' } do |f| %>
  <%= f.input :tweet_id, required: true  %>
  <%= f.button :submit %>
<% end %>

app/views/tweets/_tweets.html.erb
<% @tweets.each do |tweet| %>
  <li>
    <span id="user"><%= hyperlink_the_tings("@#{tweet.user}") %></span> <span id="content"><%= hyperlink_the_tings(tweet.content) %></span> (<span id="tweet-id"><%= tweet.tweet_id %></span>)</li>
<% end %>

app/views/tweets/index.html.erb
<div class="span6 offset3">
    <ul class="unstyled" id="tweets">
        <%= render "tweets" %>
    </ul>
    <%= link_to 'Fetch a new tweet!', new_tweet_path, :class => 'btn btn-large' %>
    <%= will_paginate @tweets %>
</div>

app/views/tweets/new.html.erb
<div class="span6 offset3">
    <section class="page-header">
        <h2>New tweet</h2>
        <% if @error %>
            <small class="label label-important"><%= @error %></small>
        <% end %>
    </section>

    <%= render 'form' %>

    <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="span6 offset3">
    <p class="alert alert-success" id="notice"><%= notice %></p>

    <ul class="unstyled">
        <li>User: <%= @tweet.user %></li>
        <li>Tweet ID: <%= @tweet.tweet_id %></li>
        <li>Status: <%= @tweet.content %></li>
    </ul>


    <%= link_to 'Back', tweets_path %> | <%= link_to 'Fetch another tweet!', new_tweet_path %>
</div>